# Streamlit Secrets 配置示例
# 在 Streamlit Cloud 或本地部署时使用

# 可选：配置不同的 API 端点
OPENAI_API_BASE = "http://localhost:1234/v1"
OPENAI_API_KEY = "lm-studio"
MODEL_NAME = "deepseek/deepseek-r1-0528-qwen3-8b"

# 生产环境示例（如果要连接到其他 API）
# OPENAI_API_BASE = "https://api.openai.com/v1"
# OPENAI_API_KEY = "your-actual-api-key"
# MODEL_NAME = "gpt-4"